// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
	KV: KVNamespace;
	SCORES_THRESHOLD: number;
	DISTANCE_LIMIT: number;
}
